//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AticAtac.rc
//
#define IDB_BITMAP_CAVE_DOOR_FRAME                  102
#define IDB_BITMAP_NORMAL_DOOR_FRAME                103
#define IDB_BITMAP_BIG_DOOR_FRAME                   104
#define IDB_BITMAP_RED_LOCKED_NORMAL_DOOR           105
#define IDB_BITMAP_GREEN_LOCKED_NORMAL_DOOR         106
#define IDB_BITMAP_CYAN_LOCKED_NORMAL_DOOR          107
#define IDB_BITMAP_YELLOW_LOCKED_NORMAL_DOOR        108
#define IDB_BITMAP_RED_LOCKED_CAVE_DOOR             109
#define IDB_BITMAP_GREEN_LOCKED_CAVE_DOOR           110
#define IDB_BITMAP_CYAN_LOCKED_CAVE_DOOR            111
#define IDB_BITMAP_YELLOW_LOCKED_CAVE_DOOR          112
#define IDB_BITMAP_CLOCK                            113
#define IDB_BITMAP_PICTURE                          114
#define IDB_BITMAP_TABLE                            115
#define IDB_BITMAP_FULL_TURKEY                      116
#define IDB_BITMAP_TURKEY_CARCASS                   117
#define IDB_BITMAP_ANTLER_TROPHY                    118
#define IDB_BITMAP_TROPHY                           119
#define IDB_BITMAP_BOOKCASE                         120
#define IDB_BITMAP_CLOSED_TRAP_DOOR                 121
#define IDB_BITMAP_OPEN_TRAP_DOOR                   122
#define IDB_BITMAP_BARREL                           123
#define IDB_BITMAP_RUG                              124
#define IDB_BITMAP_ACG_SHIELD                       125
#define IDB_BITMAP_SHIELD                           126
#define IDB_BITMAP_KNIGHT                           127
#define IDB_BITMAP_CLOSED_NORMAL_DOOR               128
#define IDB_BITMAP_OPEN_NORMAL_DOOR                 129
#define IDB_BITMAP_CLOSED_CAVE_DOOR                 130
#define IDB_BITMAP_OPEN_CAVE_DOOR                   131
#define IDB_BITMAP_ACG_EXIT_DOOR                    132
#define IDB_BITMAP_PICTURE_2                        133
#define IDB_BITMAP_SKELETON                         134
#define IDB_BITMAP_BARRELS                          135
#define IDB_BITMAP_ROOM_0                           136
#define IDB_BITMAP_ROOM_1                           137
#define IDB_BITMAP_ROOM_2                           138
#define IDB_BITMAP_ROOM_3                           139
#define IDB_BITMAP_ROOM_4                           140
#define IDB_BITMAP_ROOM_5                           141
#define IDB_BITMAP_ROOM_6                           142
#define IDB_BITMAP_ROOM_7                           143
#define IDB_BITMAP_ROOM_8                           144
#define IDB_BITMAP_ROOM_9                           145
#define IDB_BITMAP_ROOM_10                          146
#define IDB_BITMAP_ROOM_11                          147
#define IDB_BITMAP_SCROLL                           148
#define IDB_BITMAP_SCROLL_SEAL                      149
#define IDB_BITMAP_LEAF                             150
#define IDB_BITMAP_KEY                              151
#define IDB_BITMAP_BOTTLE                           152
#define IDB_BITMAP_MEDICINE_BOTTLE                  153
#define IDB_BITMAP_BROKEN                           154
#define IDB_BITMAP_ROPE                             155
#define IDB_BITMAP_ARM                              156
#define IDB_BITMAP_BOWL                             157
#define IDB_BITMAP_APPLE                            158
#define IDB_BITMAP_CANDY_BAR                        159
#define IDB_BITMAP_HAM                              160
#define IDB_BITMAP_LOLLIPOP                         161
#define IDB_BITMAP_MONEY_BAG                        162
#define IDB_BITMAP_GOBSTOPPER                       163
#define IDB_BITMAP_AMULET                           164
#define IDB_BITMAP_CAN                              165
#define IDB_BITMAP_ICE_CREAM_CONE                   166
#define IDB_BITMAP_CRUCIFIX                         167
#define IDB_BITMAP_SKULL                            168
#define IDB_BITMAP_SPANNER                          169
#define IDB_BITMAP_MUSHROOM                         170
#define IDB_BITMAP_GRAVESTONE                       171
#define IDB_BITMAP_ACG_KEY_LEFT                     172
#define IDB_BITMAP_ACG_KEY_MIDDLE                   173
#define IDB_BITMAP_ACG_KEY_RIGHT                    174
#define IDB_BITMAP_KEYBOARD_LEFT_PANE               175
#define IDB_BITMAP_KEYBOARD_RIGHT_PANE              176
#define IDB_BITMAP_CURSOR_DIRECTIONS_LEFT_PANE      177
#define IDB_BITMAP_CURSOR_DIRECTIONS_RIGHT_PANE     178
#define IDB_BITMAP_JOYSTICK_LEFT_PANE               179
#define IDB_BITMAP_JOYSTICK_RIGHT_PANE              180
#define IDB_BITMAP_KNIGHT_WALKING_DOWN_1            186
#define IDB_BITMAP_KNIGHT_WALKING_UP_1              187 
#define IDB_BITMAP_KNIGHT_DOWN                      188 
#define IDB_BITMAP_KNIGHT_WALKING_DOWN_2            189 
#define IDB_BITMAP_KNIGHT_UP                        190
#define IDB_BITMAP_KNIGHT_WALKING_UP_2              191
#define IDB_BITMAP_KNIGHT_WALKING_LEFT_1            192
#define IDB_BITMAP_KNIGHT_WALKING_RIGHT_1           193
#define IDB_BITMAP_KNIGHT_LEFT                      194
#define IDB_BITMAP_KNIGHT_WALKING_LEFT_2            195 
#define IDB_BITMAP_KNIGHT_RIGHT                     196
#define IDB_BITMAP_KNIGHT_WALKING_RIGHT_2           197
#define IDB_BITMAP_WIZARD_WALKING_DOWN_1            198
#define IDB_BITMAP_WIZARD_WALKING_UP_1              199 
#define IDB_BITMAP_WIZARD_DOWN                      200 
#define IDB_BITMAP_WIZARD_WALKING_DOWN_2            201 
#define IDB_BITMAP_WIZARD_UP                        202
#define IDB_BITMAP_WIZARD_WALKING_UP_2              203
#define IDB_BITMAP_WIZARD_WALKING_LEFT_1            204
#define IDB_BITMAP_WIZARD_WALKING_RIGHT_1           205
#define IDB_BITMAP_WIZARD_LEFT                      206
#define IDB_BITMAP_WIZARD_WALKING_LEFT_2            207
#define IDB_BITMAP_WIZARD_RIGHT                     208
#define IDB_BITMAP_WIZARD_WALKING_RIGHT_2           209
#define IDB_BITMAP_SERF_WALKING_DOWN_1              210
#define IDB_BITMAP_SERF_WALKING_UP_1                211
#define IDB_BITMAP_SERF_DOWN                        212
#define IDB_BITMAP_SERF_WALKING_DOWN_2              213
#define IDB_BITMAP_SERF_UP                          214
#define IDB_BITMAP_SERF_WALKING_UP_2                215
#define IDB_BITMAP_SERF_WALKING_LEFT_1              216
#define IDB_BITMAP_SERF_WALKING_RIGHT_1             217
#define IDB_BITMAP_SERF_LEFT                        218
#define IDB_BITMAP_SERF_WALKING_LEFT_2              219
#define IDB_BITMAP_SERF_RIGHT                       220
#define IDB_BITMAP_SERF_WALKING_RIGHT_2             221
#define IDB_BITMAP_FALLING_SIMULATION_01            222
#define IDB_BITMAP_FALLING_SIMULATION_02            223
#define IDB_BITMAP_FALLING_SIMULATION_03            224
#define IDB_BITMAP_FALLING_SIMULATION_04            225
#define IDB_BITMAP_FALLING_SIMULATION_05            226
#define IDB_BITMAP_FALLING_SIMULATION_06            227
#define IDB_BITMAP_PUMPKIN_1                        228
#define IDB_BITMAP_PUMPKIN_2                        229
#define IDB_BITMAP_SPIDER_1                         230
#define IDB_BITMAP_SPIDER_2                         231
#define IDB_BITMAP_GHOST_1                          232
#define IDB_BITMAP_GHOST_2                          233
#define IDB_BITMAP_BOUNCY_1                         234
#define IDB_BITMAP_BOUNCY_2                         235
#define IDB_BITMAP_SMORPH_1                         236
#define IDB_BITMAP_SMORPH_2                         237
#define IDB_BITMAP_JELLY_GHOUL_1                    238
#define IDB_BITMAP_JELLY_GHOUL_2                    239
#define IDB_BITMAP_BAT_1                            240
#define IDB_BITMAP_BAT_2                            241
#define IDB_BITMAP_WITCH_FLYING_LEFT_1              242
#define IDB_BITMAP_WITCH_FLYING_LEFT_2              243
#define IDB_BITMAP_WITCH_FLYING_RIGHT_1             244
#define IDB_BITMAP_WITCH_FLYING_RIGHT_2             245
#define IDB_BITMAP_GHOUL_FLYING_LEFT_1              246
#define IDB_BITMAP_GHOUL_FLYING_LEFT_2              247
#define IDB_BITMAP_GHOUL_FLYING_RIGHT_1             248
#define IDB_BITMAP_GHOUL_FLYING_RIGHT_2             249
#define IDB_BITMAP_BAT_FLYING_LEFT_1                250
#define IDB_BITMAP_BAT_FLYING_LEFT_2                251
#define IDB_BITMAP_BAT_FLYING_RIGHT_1               252
#define IDB_BITMAP_BAT_FLYING_RIGHT_2               253
#define IDB_BITMAP_GHOUL_1                          254
#define IDB_BITMAP_GHOUL_2                          255
#define IDB_BITMAP_NASTY_ALIVE_1                    256
#define IDB_BITMAP_NASTY_ALIVE_2                    257
#define IDB_BITMAP_NASTY_ALIVE_3                    258
#define IDB_BITMAP_NASTY_ALIVE_4                    259
#define IDB_BITMAP_NASTY_DEAD_1                     260
#define IDB_BITMAP_NASTY_DEAD_2                     261
#define IDB_BITMAP_NASTY_DEAD_3                     262
#define IDB_BITMAP_NASTY_DEAD_4                     263
#define IDB_BITMAP_KNIGHT_AXE_1                     264
#define IDB_BITMAP_KNIGHT_AXE_2                     265
#define IDB_BITMAP_KNIGHT_AXE_3                     266
#define IDB_BITMAP_KNIGHT_AXE_4                     267
#define IDB_BITMAP_KNIGHT_AXE_5                     268
#define IDB_BITMAP_KNIGHT_AXE_6                     269
#define IDB_BITMAP_KNIGHT_AXE_7                     270
#define IDB_BITMAP_KNIGHT_AXE_8                     271
#define IDB_BITMAP_WIZARD_POTION_1                  272
#define IDB_BITMAP_WIZARD_POTION_2                  273
#define IDB_BITMAP_WIZARD_POTION_3                  274
#define IDB_BITMAP_SERF_SWORD_1                     275
#define IDB_BITMAP_SERF_SWORD_2                     276
#define IDB_BITMAP_SERF_SWORD_3                     277
#define IDB_BITMAP_SERF_SWORD_4                     278
#define IDB_BITMAP_SERF_SWORD_5                     279
#define IDB_BITMAP_SERF_SWORD_6                     280
#define IDB_BITMAP_SERF_SWORD_7                     281
#define IDB_BITMAP_SERF_SWORD_8                     282
#define IDB_BITMAP_MUMMY_1                          283
#define IDB_BITMAP_MUMMY_2                          284
#define IDB_BITMAP_MUMMY_3                          285
#define IDB_BITMAP_DRACULA_1                        286
#define IDB_BITMAP_DRACULA_2                        287
#define IDB_BITMAP_DRACULA_3                        288
#define IDB_BITMAP_FRANKENSTEIN_1                   289
#define IDB_BITMAP_FRANKENSTEIN_2                   290
#define IDB_BITMAP_FRANKENSTEIN_3                   291
#define IDB_BITMAP_HUNCHBACK_1                      292
#define IDB_BITMAP_HUNCHBACK_2                      293
#define IDB_BITMAP_HUNCHBACK_3                      294
#define IDB_BITMAP_DEVIL_1                          295
#define IDB_BITMAP_DEVIL_2                          296
#define IDB_BITMAP_DEVIL_3                          297
#define IDB_BITMAP_LOADING_SCREEN                   298

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        299
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
