//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SabreWulf.rc
//
#define IDB_BITMAP_LOADING_SCREEN                                   102
#define IDB_BITMAP_BACKGROUND_ITEM_70bc                             103
#define IDB_BITMAP_BACKGROUND_ITEM_71b3                             104
#define IDB_BITMAP_BACKGROUND_ITEM_7298                             105
#define IDB_BITMAP_BACKGROUND_ITEM_72f6                             106
#define IDB_BITMAP_BACKGROUND_ITEM_7462                             107
#define IDB_BITMAP_BACKGROUND_ITEM_7523                             108
#define IDB_BITMAP_BACKGROUND_ITEM_771f                             109
#define IDB_BITMAP_BACKGROUND_ITEM_785e                             110
#define IDB_BITMAP_BACKGROUND_ITEM_78f2                             111
#define IDB_BITMAP_BACKGROUND_ITEM_7947                             112
#define IDB_BITMAP_BACKGROUND_ITEM_7981                             113
#define IDB_BITMAP_BACKGROUND_ITEM_7b11                             114
#define IDB_BITMAP_BACKGROUND_ITEM_7bb7                             115
#define IDB_BITMAP_BACKGROUND_ITEM_7c0c                             116
#define IDB_BITMAP_BACKGROUND_ITEM_7ccd                             117
#define IDB_BITMAP_BACKGROUND_ITEM_7e4b                             118
#define IDB_BITMAP_BACKGROUND_ITEM_8047                             119
#define IDB_BITMAP_BACKGROUND_ITEM_81c5                             120
#define IDB_BITMAP_BACKGROUND_ITEM_8382                             121
#define IDB_BITMAP_BACKGROUND_ITEM_83aa                             122
#define IDB_BITMAP_BACKGROUND_ITEM_83d2                             123
#define IDB_BITMAP_BACKGROUND_ITEM_8427                             124
#define IDB_BITMAP_BACKGROUND_ITEM_847c                             125
#define IDB_BITMAP_BACKGROUND_ITEM_8558                             126
#define IDB_BITMAP_BACKGROUND_ITEM_85c8                             127
#define IDB_BITMAP_BACKGROUND_ITEM_86da                             128
#define IDB_BITMAP_BACKGROUND_ITEM_8702                             129
#define IDB_BITMAP_BACKGROUND_ITEM_872a                             130
#define IDB_BITMAP_BACKGROUND_ITEM_8806                             131
#define IDB_BITMAP_BACKGROUND_ITEM_89c3                             132
#define IDB_BITMAP_BACKGROUND_ITEM_8b80                             133
#define IDB_BITMAP_BACKGROUND_ITEM_8c5c                             134
#define IDB_BITMAP_BACKGROUND_ITEM_8ccc                             135
#define IDB_BITMAP_BACKGROUND_ITEM_8d3c                             136
#define IDB_BITMAP_BACKGROUND_ITEM_8e18                             137
#define IDB_BITMAP_BACKGROUND_ITEM_8f2a                             138
#define IDB_BITMAP_BACKGROUND_ITEM_90a8                             139
#define IDB_BITMAP_BACKGROUND_ITEM_93c4                             140
#define IDB_BITMAP_BACKGROUND_ITEM_955d                             141
#define IDB_BITMAP_BACKGROUND_ITEM_95cd                             142
#define IDB_BITMAP_BACKGROUND_ITEM_9673                             143
#define IDB_BITMAP_BACKGROUND_ITEM_e1ec                             144
#define IDB_BITMAP_BACKGROUND_ITEM_e3a0_AMULET_PIECE_TOP_LEFT       145  
#define IDB_BITMAP_BACKGROUND_ITEM_e3a0_AMULET_BLANK_TOP_LEFT       146        
#define IDB_BITMAP_BACKGROUND_ITEM_e494_AMULET_PIECE_TOP_RIGHT      147
#define IDB_BITMAP_BACKGROUND_ITEM_e494_AMULET_BLANK_TOP_RIGHT      148      
#define IDB_BITMAP_BACKGROUND_ITEM_e588_AMULET_PIECE_BOTTOM_LEFT    149
#define IDB_BITMAP_BACKGROUND_ITEM_e588_AMULET_BLANK_BOTTOM_LEFT    150     
#define IDB_BITMAP_BACKGROUND_ITEM_e67c_AMULET_PIECE_BOTTOM_RIGHT   151   
#define IDB_BITMAP_BACKGROUND_ITEM_e67c_AMULET_BLANK_BOTTOM_RIGHT   152         
#define IDB_BITMAP_EARWIG_LEFT_1                                    153
#define IDB_BITMAP_EARWIG_LEFT_2                                    154
#define IDB_BITMAP_EARWIG_RIGHT_1                                   155
#define IDB_BITMAP_EARWIG_RIGHT_2                                   156
#define IDB_BITMAP_BUG_LEFT_1                                       157
#define IDB_BITMAP_BUG_LEFT_2                                       158
#define IDB_BITMAP_BUG_RIGHT_1                                      159
#define IDB_BITMAP_BUG_RIGHT_2                                      160
#define IDB_BITMAP_SKUNK_LEFT_1                                     161
#define IDB_BITMAP_SKUNK_LEFT_2                                     162
#define IDB_BITMAP_SKUNK_RIGHT_1                                    163
#define IDB_BITMAP_SKUNK_RIGHT_2                                    164
#define IDB_BITMAP_BAT_LEFT_1                                       165
#define IDB_BITMAP_BAT_LEFT_2                                       166
#define IDB_BITMAP_BAT_RIGHT_1                                      167
#define IDB_BITMAP_BAT_RIGHT_2                                      168
#define IDB_BITMAP_SABRE_MAN_WALKING_UP_1                           169
#define IDB_BITMAP_SABRE_MAN_UP                                     170
#define IDB_BITMAP_SABRE_MAN_WALKING_UP_2                           171
#define IDB_BITMAP_SABRE_MAN_WALKING_DOWN_1                         172
#define IDB_BITMAP_SABRE_MAN_DOWN                                   173
#define IDB_BITMAP_SABRE_MAN_WALKING_DOWN_2                         174
#define IDB_BITMAP_SABRE_MAN_WALKING_LEFT_1                         175
#define IDB_BITMAP_SABRE_MAN_LEFT                                   176
#define IDB_BITMAP_SABRE_MAN_WALKING_LEFT_2                         177
#define IDB_BITMAP_SABRE_MAN_SWORD_LEFT_1                           178
#define IDB_BITMAP_SABRE_MAN_SWORD_LEFT_2                           179
#define IDB_BITMAP_SABRE_MAN_SWORD_LEFT_3                           180
#define IDB_BITMAP_SABRE_MAN_SWORD_LEFT_4                           186
#define IDB_BITMAP_SABRE_MAN_SWORD_LEFT_5                           187
#define IDB_BITMAP_SABRE_MAN_SWORD_LEFT_6                           188
#define IDB_BITMAP_SABRE_MAN_WALKING_RIGHT_1                        189
#define IDB_BITMAP_SABRE_MAN_RIGHT                                  190
#define IDB_BITMAP_SABRE_MAN_WALKING_RIGHT_2                        191
#define IDB_BITMAP_SABRE_MAN_SWORD_RIGHT_1                          192
#define IDB_BITMAP_SABRE_MAN_SWORD_RIGHT_2                          193
#define IDB_BITMAP_SABRE_MAN_SWORD_RIGHT_3                          194
#define IDB_BITMAP_SABRE_MAN_SWORD_RIGHT_4                          195
#define IDB_BITMAP_SABRE_MAN_SWORD_RIGHT_5                          196
#define IDB_BITMAP_SABRE_MAN_SWORD_RIGHT_6                          197
#define IDB_BITMAP_RHINOCEROS_RUNNING_LEFT_2                        198
#define IDB_BITMAP_RHINOCEROS_RUNNING_LEFT_1                        199
#define IDB_BITMAP_RHINOCEROS_RUNNING_RIGHT_2                       200
#define IDB_BITMAP_RHINOCEROS_RUNNING_RIGHT_1                       201
#define IDB_BITMAP_HIPPOPOTAMUS_SLEEPING                            202
#define IDB_BITMAP_HIPPOPOTAMUS_RUNNING_LEFT_1                      203
#define IDB_BITMAP_HIPPOPOTAMUS_RUNNING_LEFT_2                      204
#define IDB_BITMAP_HIPPOPOTAMUS_RUNNING_RIGHT_1                     205
#define IDB_BITMAP_HIPPOPOTAMUS_RUNNING_RIGHT_2                     206
#define IDB_BITMAP_INDIAN_LEFT_1                                    207
#define IDB_BITMAP_INDIAN_LEFT_2                                    208
#define IDB_BITMAP_INDIAN_LEFT_3                                    209
#define IDB_BITMAP_INDIAN_RIGHT_1                                   210
#define IDB_BITMAP_INDIAN_RIGHT_2                                   211
#define IDB_BITMAP_INDIAN_RIGHT_3                                   212
#define IDB_BITMAP_SPIDER_LEFT_1                                    213
#define IDB_BITMAP_SPIDER_LEFT_2                                    214
#define IDB_BITMAP_SPIDER_RIGHT_1                                   215
#define IDB_BITMAP_SPIDER_RIGHT_2                                   216
#define IDB_BITMAP_SCORPION_LEFT_1                                  217
#define IDB_BITMAP_SCORPION_LEFT_2                                  218
#define IDB_BITMAP_SCORPION_RIGHT_1                                 219
#define IDB_BITMAP_SCORPION_RIGHT_2                                 220
#define IDB_BITMAP_WOLF_WALKING_LEFT_1                              221
#define IDB_BITMAP_WOLF_WALKING_LEFT_2                              222
#define IDB_BITMAP_WOLF_WALKING_LEFT_3                              223
#define IDB_BITMAP_WOLF_WALKING_RIGHT_1                             224
#define IDB_BITMAP_WOLF_WALKING_RIGHT_2                             225
#define IDB_BITMAP_WOLF_WALKING_RIGHT_3                             226
#define IDB_BITMAP_WOLF_JUMPING_LEFT_1                              227
#define IDB_BITMAP_WOLF_JUMPING_LEFT_2                              228
#define IDB_BITMAP_WOLF_JUMPING_RIGHT_1                             229
#define IDB_BITMAP_WOLF_JUMPING_RIGHT_2                             230
#define IDB_BITMAP_SABRE_MAN_FALLING_LEFT                           231
#define IDB_BITMAP_SABRE_MAN_FALLING_RIGHT                          232
#define IDB_BITMAP_SABRE_MAN_SITTING_LEFT                           233
#define IDB_BITMAP_SABRE_MAN_SITTING_RIGHT                          234
#define IDB_BITMAP_SABRE_MAN_GAME_OVER_LEFT                         235
#define IDB_BITMAP_SABRE_MAN_GAME_OVER_RIGHT                        236
#define IDB_BITMAP_ORCHID_1                                         237
#define IDB_BITMAP_ORCHID_2                                         238
#define IDB_BITMAP_ORCHID_3                                         239
#define IDB_BITMAP_ORCHID_4                                         240
#define IDB_BITMAP_ORCHID_5                                         241
#define IDB_BITMAP_ORCHID_6                                         242
#define IDB_BITMAP_ORCHID_7                                         243
#define IDB_BITMAP_ORCHID_8                                         244
#define IDB_BITMAP_PARROT_LEFT_1                                    245
#define IDB_BITMAP_PARROT_LEFT_2                                    246
#define IDB_BITMAP_PARROT_RIGHT_1                                   247
#define IDB_BITMAP_PARROT_RIGHT_2                                   248
#define IDB_BITMAP_MONKEY_LEFT_1                                    249
#define IDB_BITMAP_MONKEY_LEFT_2                                    250
#define IDB_BITMAP_MONKEY_RIGHT_1                                   251
#define IDB_BITMAP_MONKEY_RIGHT_2                                   252
#define IDB_BITMAP_LIZARD_LEFT_1                                    253
#define IDB_BITMAP_LIZARD_LEFT_2                                    254
#define IDB_BITMAP_LIZARD_RIGHT_1                                   255
#define IDB_BITMAP_LIZARD_RIGHT_2                                   256
#define IDB_BITMAP_SNAKE_LEFT_1                                     257
#define IDB_BITMAP_SNAKE_LEFT_2                                     258
#define IDB_BITMAP_SNAKE_RIGHT_1                                    259
#define IDB_BITMAP_SNAKE_RIGHT_2                                    260
#define IDB_BITMAP_NASTY_DEAD_4                                     261
#define IDB_BITMAP_NASTY_DEAD_1                                     262
#define IDB_BITMAP_NASTY_DEAD_2                                     263
#define IDB_BITMAP_NASTY_DEAD_3                                     264
#define IDB_BITMAP_NASTY_ALIVE_1                                    265
#define IDB_BITMAP_NASTY_ALIVE_2                                    266
#define IDB_BITMAP_NASTY_ALIVE_3                                    267
#define IDB_BITMAP_NASTY_ALIVE_4                                    268
#define IDB_BITMAP_NASTY_ALIVE_5                                    269
#define IDB_BITMAP_NASTY_ALIVE_6                                    270
#define IDB_BITMAP_BOX                                              271
#define IDB_BITMAP_RING                                             272
#define IDB_BITMAP_APPLE                                            273
#define IDB_BITMAP_CHARM                                            274
#define IDB_BITMAP_AMULET                                           275
#define IDB_BITMAP_EXTRA_LIFE                                       276
#define IDB_BITMAP_MONEY_BAG                                        277
#define IDB_BITMAP_SPEAR                                            278
#define IDB_BITMAP_CHALICE                                          279
#define IDB_BITMAP_WARTHOG_SLEEPING                                 280
#define IDB_BITMAP_WARTHOG_RUNNING_LEFT_1                           281
#define IDB_BITMAP_WARTHOG_RUNNING_LEFT_2                           282
#define IDB_BITMAP_WARTHOG_RUNNING_RIGHT_1                          283
#define IDB_BITMAP_WARTHOG_RUNNING_RIGHT_2                          284
#define IDB_BITMAP_AMULET_PIECE_TOP_LEFT                            285
#define IDB_BITMAP_AMULET_PIECE_TOP_RIGHT                           286
#define IDB_BITMAP_AMULET_PIECE_BOTTOM_LEFT                         287
#define IDB_BITMAP_AMULET_PIECE_BOTTOM_RIGHT                        288
#define IDB_BITMAP_GUARDIAN_1                                       289
#define IDB_BITMAP_GUARDIAN_2                                       290
#define IDB_BITMAP_FIRE_1                                           291
#define IDB_BITMAP_FIRE_2                                           292
#define IDB_BITMAP_FIRE_3                                           293
#define IDB_BITMAP_FIRE_4                                           294
#define IDB_BITMAP_RAT_LEFT_1                                       295
#define IDB_BITMAP_RAT_LEFT_2                                       296
#define IDB_BITMAP_RAT_RIGHT_1                                      297
#define IDB_BITMAP_RAT_RIGHT_2                                      298
#define IDB_BITMAP_BIRD_LEFT_1                                      299
#define IDB_BITMAP_BIRD_LEFT_2                                      300
#define IDB_BITMAP_BIRD_RIGHT_1                                     301
#define IDB_BITMAP_BIRD_RIGHT_2                                     302
#define IDB_BITMAP_FLY_LEFT_1                                       303
#define IDB_BITMAP_FLY_LEFT_2                                       304
#define IDB_BITMAP_FLY_RIGHT_1                                      305
#define IDB_BITMAP_FLY_RIGHT_2                                      306
#define IDB_BITMAP_FROG_LEFT_1                                      307
#define IDB_BITMAP_FROG_LEFT_2                                      308
#define IDB_BITMAP_FROG_RIGHT_1                                     309
#define IDB_BITMAP_FROG_RIGHT_2                                     310
                                                                   
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        311
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
